name: Challenge 1
on: [push]
jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - name: Print date
      run: date
  job-2:
    name: Job 2
    runs-on: windows-latest
    steps:
    - name: Print date
      run: Get-Date
  job-3:
    name: Job 3
    runs-on: macos-latest
    steps:
    - name: Print date
      run: date
  job-4:
    name: Job 4
    runs-on: ubuntu-18.04
    needs: [job-1, job-2, job-3]
    steps:
    - name: Print date
      run: date
