name: Challenge 3
on: [push]
env:
  APP_NAME: hello
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test hello.py
        run: python hello.py | grep "Hello, world" || exit 1
  build:
    needs: [test]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.APP_NAME }}-${{ github.sha }}"
          path: hello.py
